# Generated by Django 5.2.4 on 2025-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_order_status_alter_order_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
