# Generated by Django 5.2.4 on 2025-08-12 13:42

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_remove_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="last_date",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
