# Generated by Django 5.2.4 on 2025-08-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_order_last_date_alter_order_date_ordered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="last_date",
            new_name="last_update",
        ),
    ]
