# Generated by Django 5.2.4 on 2025-08-13 13:38

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_rename_last_date_order_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="last_update",
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
