# Generated by Django 5.2.4 on 2025-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_add_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("processing", "در حال پردازش"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل داده شده"),
                    ("cancelled", "لغو شده"),
                    ("failed", "پرداخت ناموفق"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
