# Generated by Django 5.2.4 on 2025-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address1",
            new_name="shipping_email",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address2",
            new_name="shipping_fullName",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="email",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="my_cart",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="state",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_address1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_address2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_phone",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_zipcode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
