# Generated by Django 5.2.4 on 2025-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_shipping_fullname_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("processing", "در حال پردازش"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل داده شده"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fullName",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="shipping_fullName",
            field=models.CharField(max_length=255),
        ),
    ]
