# Generated by Django 5.2.4 on 2025-08-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
