# Generated by Django 5.2.4 on 2025-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_star"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
