# Generated by Django 5.2.4 on 2025-08-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_profile_old_cart_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='old_cart',
            new_name='my_cart',
        ),
    ]
